### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by schoenwaldnils** [watermarkchurch/ts-generators#26]
It seems no commonJS code generated when published.
No dist folder in `node_modules/contentful-ts-generator`

I get this error when trying to use it:
```
Error: Cannot find module 'node_modules/contentful-ts-generator/dist/index.js'. 
Please verify that the package.json has a valid "main" entry
```

**Comment by gburgett** [comment]
Ah that's my fault!  My automation didn't ensure that the dist directory existed before publishing.  I've fixed that now.  Please try v0.2.9.
