### ISSUE TITLE
Type definitions are being omitted for environments with >100 content types

### ISSUE THREAD

**Issue by Ben-Kincaid** [watermarkchurch/ts-generators#48]
Attempting to generate type definitions for environments with >100 content types will omit the type definitions for (seemingly arbitrary) content types after that limit is reached. Seems to be caused by Contentful's default limit of 100 on their entry/content_type queries. https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/reverse-order

https://github.com/watermarkchurch/contentful-ts-generator/pull/47 addresses this by increasing this limit to the maximum allowed value for the `getContentTypes` call.

**Comment by gburgett** [comment]
Released in v0.2.12
